name: EcoCrates
version: ${projectVersion}
main: com.willfp.ecocrates.EcoCratesPlugin
api-version: 1.17
authors: [ Auxilor ]
website: willfp.com
load: STARTUP
depend:
  - eco
  - ProtocolLib
softdepend:
  - CrateReloaded
  - ExcellentCrates
  - CrazyCrates
  - SpecializedCrates

commands:
  ecocrates:
    aliases:
      - crates
      - crate
    description: Base plugin command
    permission: ecocrates.command.ecocrates

permissions:
  ecocrates.*:
    description: All ecocrates permissions
    default: op
    children:
      ecocrates.command.reload: true
      ecocrates.command.ecocrates: true
      ecocrates.command.give: true
      ecocrates.command.open: true
      ecocrates.command.preview: true
      ecocrates.command.keys: true
      ecocrates.command.set: true
      ecocrates.command.forceopen: true
      ecocrates.command.resetwins: true
      ecocrates.command.convert: true
      ecocrates.command.giveall: true
      ecocrates.break: true
      ecocrates.open.*: true

  ecocrates.command.ecocrates:
    description: Allows the use of /ecocrates (base command)
    default: true
  ecocrates.command.reload:
    description: Allows reloading the config
    default: op
  ecocrates.command.give:
    description: Allows giving players keys
    default: op
  ecocrates.command.giveall:
    description: Allows giving all players keys
    default: op
  ecocrates.command.open:
    description: Allows opening crates with /ecocrates open
    default: true
  ecocrates.command.forceopen:
    description: Allows opening crates with /ecocrates forceopen
    default: op
  ecocrates.command.preview:
    description: Allows previewing crates with /ecocrates preview
    default: true
  ecocrates.command.keys:
    description: Allows viewing owned keys with /ecocrates keys
    default: true
  ecocrates.command.set:
    description: Allows marking a block as a crate
    default: op
  ecocrates.command.resetwins:
    description: Allows resetting a players tracked reward wins
    default: op
  ecocrates.command.convert:
    description: Allows converting crates over from other plugins
    default: op
  ecocrates.break:
    description: Allows breaking crate blocks
    default: op
  ecocrates.open.*:
    description: Allows opening all crates
    default: true
